Provide a workaround for token permission issues
impress-org/givewp pull request #5200
Opened 2020-08-25 16:48 UTC by JasonTheAdams

## Description

PayPal has a known issue they're working on wherein an access token generated from the `authorization_code` grant type does not have the proper permissions to generate a Subscription. Unfortunately, this is the exact grant type used during the onboarding process.

This PR provides a workaround where it uses the client credentials retrieved during onboarding to replace the stored token details with a token generated from the `client_credentials` grant type. This token has the correct permissions.

## Affects

The PayPal Commerce onboarding process, refreshing the token, and usage of the token for donations.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2020-08-25 16:48 UTC, JasonTheAdams commented
@ravinderk Here is the workaround. Please review and merge if it's good.

2020-08-25 18:28 UTC, JasonTheAdams commented
@ravinderk Updated the description to reflect my latest findings.

2020-08-25 19:35 UTC, ravinderk requested changes
@JasonTheAdams I am not able to onboard user.

<img width="1277" alt="Image 2020-08-26 at 1 04 06 AM" src="https://user-images.githubusercontent.com/1784821/91219383-2dc08d00-e738-11ea-8e70-aa8bab74b7c1.png">

2020-08-25 19:35 UTC, ravinderk commented on src/PaymentGateways/PayPalCommerce/AjaxRequestHandler.php
>  		MerchantDetails $merchantRepository,
@JasonTheAdams Did you forget to initiate `payPalAuth`?

2020-08-25 20:05 UTC, JasonTheAdams commented
@ravinderk I've fixed a couple issue. Please review again.

2020-08-26 06:36 UTC, ravinderk approved these changes
@JasonTheAdams Working fine for me.

2020-08-26 06:37 UTC, merged