Reporting Revenue is now more performant and scaleable
impress-org/givewp pull request #5476
Opened 2020-11-24 19:10 UTC by kjohnson

Resolves #5475

## Description

## Affects

## Visuals

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@since` tags included in DocBlocks
-   [ ] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

2020-12-01 10:29 UTC, ravinderk requested changes
@kjohnson Relocation file can cause of fatal error.

I found one conflict with Funds addon in which we are using `src/API/Endpoints/Reports/Endpoint.php`.

Can we keep backward compatibility if rename and relocation files is necessary?

2020-12-01 15:25 UTC, kjohnson commented
@ravinderk where in `give-funds` are we using the reports endpoint class?

Do you mean `Give\API\RestRoute`?

2020-12-01 15:27 UTC, ravinderk commented
@kjohnson You are correct, I got this error:

```
[01-Dec-2020 10:20:58 UTC] PHP Fatal error:  Interface 'Give\API\RestRoute' not found in /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give-funds/src/Routes/Endpoint.php on line 14
```

2020-12-01 15:39 UTC, kjohnson commented
@ravinderk resolved the `API/RestRoute` backwards compatibility by 5ce355da9

2020-12-03 07:06 UTC, ravinderk requested changes
@kjohnson I think update report endpoints are not loading correctly. I am setting unexpected results on the `Report page`.

![image](https://user-images.githubusercontent.com/1784821/100975443-0877c200-3564-11eb-8ade-d77f9ed7cb58.png)

2020-12-04 19:22 UTC, kjohnson commented
@ravinderk Hmm... Do you have some test data seeded in the database?

Can you inspect the network calls and see if there are any errors?

Here is my side by side comparison of develop vs the changes in this branch. The only difference is that develop never finished loading the top donors section.

| Develop | Branch |
| --- | --- |
| ![Screen Shot 2020-12-04 at 14 18 24](https://user-images.githubusercontent.com/10858303/101205600-d9348400-363b-11eb-8850-82f196d90e62.png) | ![Screen Shot 2020-12-04 at 14 20 39](https://user-images.githubusercontent.com/10858303/101205628-e6517300-363b-11eb-980f-45c1226e4479.png) |

2021-01-04 11:17 UTC, ravinderk commented
@kjohnson I can see inconsistency in results. We catch these issues with unit tests but we did not have enough tests. Before merging this pr, we can write more tests to catch inconsistent results.

| Develop | Branch |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1784821/103529421-a801da80-4eab-11eb-8686-4213faf94bc5.png) | ![image](https://user-images.githubusercontent.com/1784821/103529595-f31bed80-4eab-11eb-8178-f2b3ac4e8b20.png) |

2021-01-04 19:16 UTC, kjohnson commented
@ravinderk are you seeing any inconsistencies other than the Top Donor widget?

In my comparison (using All Time), the Top Donor timed out on `develop`, so this widget I did not compare.

2021-01-04 19:31 UTC, kjohnson commented
@ravinderk I reverted the custom query that I wrote for Top Donors and instead rely upon the improvements to the underlying `getPayments()` improvements.

2021-01-05 11:19 UTC, ravinderk commented
@kjohnson Get rid of the custom query will not resolve the issue and the requested api response still will be different from the previous one. Under the hood `BaseEndpoint::getPayments` perform custom query.

I also notice that I was not able to see donor Gravatars under the `Top Donors` card.

| Current | Develop
|---------|---------|
|![image](https://user-images.githubusercontent.com/1784821/103640099-6f2e3800-4f75-11eb-93a4-465c115516d8.png)|![image](https://user-images.githubusercontent.com/1784821/103640202-96850500-4f75-11eb-8662-0000f7c50214.png)|

I am getting following PHP errors when load Reports page:

```
[05-Jan-2021 11:04:21 UTC] PHP Warning:  array_filter() expects parameter 1 to be array, float given in /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Reports/Endpoints/TotalIncome.php on line 72
[05-Jan-2021 11:04:21 UTC] PHP Stack trace:
[05-Jan-2021 11:04:21 UTC] PHP   1. {main}() /Users/ravinderkumar/Local-Sites/give/app/public/index.php:0
[05-Jan-2021 11:04:21 UTC] PHP   2. require() /Users/ravinderkumar/Local-Sites/give/app/public/index.php:17
[05-Jan-2021 11:04:21 UTC] PHP   3. wp() /Users/ravinderkumar/Local-Sites/give/app/public/wp-blog-header.php:16
[05-Jan-2021 11:04:21 UTC] PHP   4. WP->main() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/functions.php:1291
[05-Jan-2021 11:04:21 UTC] PHP   5. WP->parse_request() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp.php:745
[05-Jan-2021 11:04:21 UTC] PHP   6. do_action_ref_array() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp.php:388
[05-Jan-2021 11:04:21 UTC] PHP   7. WP_Hook->do_action() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/plugin.php:551
[05-Jan-2021 11:04:21 UTC] PHP   8. WP_Hook->apply_filters() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp-hook.php:311
[05-Jan-2021 11:04:21 UTC] PHP   9. rest_api_loaded() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp-hook.php:287
[05-Jan-2021 11:04:21 UTC] PHP  10. WP_REST_Server->serve_request() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/rest-api.php:354
[05-Jan-2021 11:04:21 UTC] PHP  11. WP_REST_Server->dispatch() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/rest-api/class-wp-rest-server.php:440
[05-Jan-2021 11:04:21 UTC] PHP  12. WP_REST_Server->respond_to_request() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/rest-api/class-wp-rest-server.php:1007
[05-Jan-2021 11:04:21 UTC] PHP  13. Give\Reports\Endpoints\TotalIncome->handleRequest() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/rest-api/class-wp-rest-server.php:1160
[05-Jan-2021 11:04:21 UTC] PHP  14. Give\Reports\Endpoints\TotalIncome->getReport() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Reports/Endpoints/BaseEndpoint.php:122
[05-Jan-2021 11:04:21 UTC] PHP  15. Give\Reports\Endpoints\TotalIncome->get_data() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Reports/Endpoints/TotalIncome.php:32
[05-Jan-2021 11:04:21 UTC] PHP  16. array_filter() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Reports/Endpoints/TotalIncome.php:72
[05-Jan-2021 11:04:21 UTC] PHP Warning:  array_filter() expects parameter 1 to be array, float given in /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Reports/Endpoints/TotalIncome.php on line 72
[05-Jan-2021 11:04:21 UTC] PHP Stack trace:
[05-Jan-2021 11:04:21 UTC] PHP   1. {main}() /Users/ravinderkumar/Local-Sites/give/app/public/index.php:0
[05-Jan-2021 11:04:21 UTC] PHP   2. require() /Users/ravinderkumar/Local-Sites/give/app/public/index.php:17
[05-Jan-2021 11:04:21 UTC] PHP   3. wp() /Users/ravinderkumar/Local-Sites/give/app/public/wp-blog-header.php:16
[05-Jan-2021 11:04:21 UTC] PHP   4. WP->main() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/functions.php:1291
[05-Jan-2021 11:04:21 UTC] PHP   5. WP->parse_request() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp.php:745
[05-Jan-2021 11:04:21 UTC] PHP   6. do_action_ref_array() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp.php:388
[05-Jan-2021 11:04:21 UTC] PHP   7. WP_Hook->do_action() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/plugin.php:551
[05-Jan-2021 11:04:21 UTC] PHP   8. WP_Hook->apply_filters() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp-hook.php:311
[05-Jan-2021 11:04:21 UTC] PHP   9. rest_api_loaded() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp-hook.php:287
[05-Jan-2021 11:04:21 UTC] PHP  10. WP_REST_Server->serve_request() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/rest-api.php:354
[05-Jan-2021 11:04:21 UTC] PHP  11. WP_REST_Server->dispatch() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/rest-api/class-wp-rest-server.php:440
[05-Jan-2021 11:04:21 UTC] PHP  12. WP_REST_Server->respond_to_request() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/rest-api/class-wp-rest-server.php:1007
[05-Jan-2021 11:04:21 UTC] PHP  13. Give\Reports\Endpoints\TotalIncome->handleRequest() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/rest-api/class-wp-rest-server.php:1160
[05-Jan-2021 11:04:21 UTC] PHP  14. Give\Reports\Endpoints\TotalIncome->getReport() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Reports/Endpoints/BaseEndpoint.php:122
[05-Jan-2021 11:04:21 UTC] PHP  15. Give\Reports\Endpoints\TotalIncome->get_data() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Reports/Endpoints/TotalIncome.php:32
[05-Jan-2021 11:04:21 UTC] PHP  16. array_filter() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Reports/Endpoints/TotalIncome.php:72
[05-Jan-2021 11:04:21 UTC] PHP Warning:  array_filter() expects parameter 1 to be array, float given in /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Reports/Endpoints/TotalIncome.php on line 72
[05-Jan-2021 11:04:21 UTC] PHP Stack trace:
[05-Jan-2021 11:04:21 UTC] PHP   1. {main}() /Users/ravinderkumar/Local-Sites/give/app/public/index.php:0
[05-Jan-2021 11:04:21 UTC] PHP   2. require() /Users/ravinderkumar/Local-Sites/give/app/public/index.php:17
[05-Jan-2021 11:04:21 UTC] PHP   3. wp() /Users/ravinderkumar/Local-Sites/give/app/public/wp-blog-header.php:16
[05-Jan-2021 11:04:21 UTC] PHP   4. WP->main() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/functions.php:1291
[05-Jan-2021 11:04:21 UTC] PHP   5. WP->parse_request() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp.php:745
[05-Jan-2021 11:04:21 UTC] PHP   6. do_action_ref_array() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp.php:388
[05-Jan-2021 11:04:21 UTC] PHP   7. WP_Hook->do_action() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/plugin.php:551
[05-Jan-2021 11:04:21 UTC] PHP   8. WP_Hook->apply_filters() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp-hook.php:311
[05-Jan-2021 11:04:21 UTC] PHP   9. rest_api_loaded() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp-hook.php:287
[05-Jan-2021 11:04:21 UTC] PHP  10. WP_REST_Server->serve_request() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/rest-api.php:354
[05-Jan-2021 11:04:21 UTC] PHP  11. WP_REST_Server->dispatch() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/rest-api/class-wp-rest-server.php:440
[05-Jan-2021 11:04:21 UTC] PHP  12. WP_REST_Server->respond_to_request() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/rest-api/class-wp-rest-server.php:1007
[05-Jan-2021 11:04:21 UTC] PHP  13. Give\Reports\Endpoints\TotalIncome->handleRequest() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/rest-api/class-wp-rest-server.php:1160
[05-Jan-2021 11:04:21  [...]

2021-01-06 19:24 UTC, kjohnson commented
I've added the donor email, so gravatars should now show - I didn't see this earlier because on `develop` "Top Donors" wouldn't even load at scale.

Also, I added support for Order By, although every report endpoint orders by date DESC - so this could probably be refactored out. The date column is always used even though it is a parameter, but the order direction is fixed.

@ravinderk can you check again for inconsistencies? I've mapped all of the existing `$args` to the new query. The query will be different, but it has to be different for "All Time" donations to process under load.

Another note: With this change I am sometimes seeing a difference in the "Revenue for Period" chart - I think this is because of a change to the date ranges. On `develop`, the end date string is appended with `24:00:00`, which causes an error in the MySQL syntax. In this change, the end string is appended with `23:59:59`

2021-02-16 10:53 UTC, ravinderk requested changes
@kjohnson I only see an issue with `Total Revenue Trends`. I also suggested updating the `@since` tag.

2021-02-16 10:53 UTC, ravinderk commented on src/Reports/Endpoints/TotalIncome.php
> +		// $prevIncome    = $this->get_income( $prevStart->format( 'Y-m-d' ), $prevEnd->format( 'Y-m-d' ) );
@kjohnson Can explain how you are calculating trends with the same data? I can not see trends in `Total Revenue`

![image](https://user-images.githubusercontent.com/1784821/108051910-7450cd80-7071-11eb-9681-dcaf714d368f.png)

2021-02-16 10:53 UTC, ravinderk commented on src/Reports/PaymentsQuery.php
> +			WHERE Donation.post_type = 'give_payment'
@kjohnson We are not querying renewals in this query. After discussion with @JasonTheAdams, I opened an issue to make renewal queriable with a simple query https://github.com/impress-org/give-recurring/issues/1030

2021-02-16 10:53 UTC, ravinderk commented on src/Reports/ServiceProvider.php
> +	 * @since 2.8.0
@kjohnson Can we update all `@since` tags to `2.10.0`

2021-02-16 10:53 UTC, ravinderk commented on src/Reports/PaymentsQuery.php
> +/**
@kjohnson `@since` tags are missing from most of the files? Can we add it?

2021-02-16 10:53 UTC, ravinderk commented on src/Reports/Endpoints/BaseEndpoint.php
> +	 * @since 2.9.5 Replaced `Give_Payments_Query` with an optimized query.
@kjohnson Can we update the `@since` tag to `2.10.0`

2021-03-03 21:36 UTC, kjohnson commented
Closing this for now - I'll revisit after scaffolding some tests for Reports.

2021-03-03 21:36 UTC, closed without merging