Hide state field for South Korea
impress-org/givewp pull request #5532
Opened 2020-12-27 07:17 UTC by jgreys

## Description

The status field is not required and not used for Korean addresses. In order to fix this, the "hidden" parameter should be set to "True" when South Korea is selected as country.

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

1. Select "South Korea" as country.
2. State field should be hidden.

2021-01-04 07:10 UTC, ravinderk commented
@jgreys
- Can you confirm that South Korea has `Province` instead of state?
- Do you have to mention the `Province` in the address?
   if yes that we can rename the `state` field label `State` to `Province` to resolve the confusion as we are doing in the `give_get_country_locale` function for other countries. For example `CA`

2021-01-04 07:11 UTC, ravinderk requested changes
@jgreys
- Can you confirm that South Korea has `Province` instead of state?
- Do you have to mention the `Province` in the address?
   if yes that we can rename the `state` field label `State` to `Province` to resolve the confusion as we are doing in the `give_get_country_locale` function for other countries. For example `CA`

2021-01-05 06:38 UTC, ravinderk approved these changes
@DevinWalker @kjohnson I reviewed the Woocommerce plugin and find out that the state field is not necessary when the donor country set to `South Korea`. Changes in this pull request look good to me but I am open to a second opinion.

![image](https://user-images.githubusercontent.com/1784821/103614273-3c247e00-4f4e-11eb-9055-2af2fdb55158.png)

2021-01-05 08:41 UTC, jgreys commented
I'm living in Korea for a little bit more than 7 years now and I've rarely seen the "Province" field in Korean websites.

Koreans use an address autocompletion system similar to what Google offers but based on the postal code. (http://postcode.map.daum.net/guide)

I integrated this solution to WooCommerce with my plugin "Korea for WooCommerce" (https://github.com/jgreys/korea-for-woocommerce). Also, I'm working on a similar solution for Give these days. :)

Lastly, here are 2 screenshots of extremely popular sites in Korea (Naver & CJmall) that support my point. Naver is like the Korean Google here.

<img width="518" alt="Screenshot 2021-01-05 at 16 56 18" src="https://user-images.githubusercontent.com/4136890/103624552-0a76db80-4f7d-11eb-85b8-9cb70596103b.png" alt="Naver" alt="Naver" />

<img width="1080" alt="Screenshot 2021-01-05 at 17 03 48" src="https://user-images.githubusercontent.com/4136890/103624541-06e35480-4f7d-11eb-9cb6-bf956b422e2e.png" alt="CJmall" alt="CJmall" />

2021-01-05 10:38 UTC, merged