Invert the zipRequired value for required indicator
impress-org/givewp pull request #5627
Opened 2021-02-22 02:22 UTC by jgreys

Resolves #5626 

## Description

The state parameter in toggleClass function should be inverted. If the zipcode is required, then it should return "false" instead of "true" so it can properly display or hide the required indicator.

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@since` tags included in DocBlocks
-   [ ] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

1. Go to a donation form
2. Select a country where the zipcode is required
3. Scroll down to zipcode field
4. Required indicator is displayed

2021-02-24 15:07 UTC, kjohnson commented
To clarify context and testing procedures for our team:
- This affects the Legacy Form template.
- I used Canada (zip required) and Yemen (zip not required) to test the fix.

Additionally, here are some screenshots of the implemented solution:

| Canada (zip required) | Yemen (zip not required) |
| --- | --- |
| ![Screenshot_2021-02-24 Donation Form – WordPress(1)](https://user-images.githubusercontent.com/10858303/109020350-e2a41a00-7687-11eb-90b9-33d31367752f.png) | ![Screenshot_2021-02-24 Donation Form – WordPress](https://user-images.githubusercontent.com/10858303/109020370-e637a100-7687-11eb-8bf2-628574b677ca.png) |

2021-02-24 15:09 UTC, kjohnson requested changes
@jgreys thanks for the contribution! This looks straight forward and your fix works as expected.

All we need now is an update to `CHANGELOG.md`, if you could add the following under `## Unreleased`, with a sub-section header of `### Fixed`:

`-   Zip Code required field indicator now toggles correctly for the Legacy Form template (#5627)`

You can use previous release notes for a formatting example.

2021-03-01 16:18 UTC, kjohnson approved these changes
Silly me - I can update the changelog with a local merge. No need to hold this up for changes!

2021-03-01 16:20 UTC, merged

2021-03-01 16:21 UTC, kjohnson commented
Again, @jgreys thanks for jumping in and fixing that bug!

2021-03-02 07:25 UTC, jgreys commented
@kjohnson You're welcome! :)

I've also spotted a bug in one of your add-on. I can provide a fix if you are interested! :)

2021-03-02 16:09 UTC, kjohnson commented
@jgreys of course! The add-ons are in private repositories, but if you could provide a [git diff patch](https://git-scm.com/docs/diff-generate-patch) and upload to as a [GitHub gist](https://gist.github.com/) then I can get that resolved.

2021-03-04 06:35 UTC, jgreys commented
@kjohnson Thanks, I will prepare this. Do you mind to contact me through my email so I can provide you the secret gist?

Here is my email: j.grzes@greys.co
Thanks! :)

2021-03-04 15:01 UTC, kjohnson commented
@jgreys yeah, that works for me - email sent.