Donation tooltips are now escaped properly
impress-org/givewp pull request #5877
Opened 2021-07-13 22:00 UTC by JasonTheAdams

Resolves #5876 

## Description

This tackles the problem that tooltips weren't being escaped properly, allowing in side-effects. The issue was that the tooltip being rendered was simply grabbing the node text without escaping it, and applying it directly to the attribute.

## Affects

Donation tooltip options

## Visuals

![Image 2021-07-13 at 2 58 31 PM](https://user-images.githubusercontent.com/2024145/125530761-09d918ea-ba21-46c2-af69-8a70aff47bfb.jpg)

![Image 2021-07-13 at 2 59 04 PM](https://user-images.githubusercontent.com/2024145/125530817-1e6b3bb4-5960-4f1c-b1ed-8b5baad226e8.jpg)

## Testing Instructions

Set the following as the Text for a Donation Option: `"onmouseover=alert(/OOPS/)//`, then hover over that donation option in the form. It **should now** open an alert.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@since` tags included in DocBlocks
-   [ ] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [ ] Includes unit and/or end-to-end tests
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2021-07-13 22:00 UTC, JasonTheAdams commented
@knowler Can you please review this when you get a chance?

2021-07-20 17:22 UTC, JasonTheAdams commented
@knowler Friendly reminder to review this when you get a chance.

2021-07-20 18:49 UTC, knowler requested changes
I have one request, otherwise this is good to go.

2021-07-20 18:49 UTC, knowler commented on src/Views/Form/Templates/Sequoia/assets/js/form.js
> +						wrap.setAttribute('rel', 'tooltip');
I know this was there before, but `rel="tooltip"` is non-standard. We should be able to get rid of it — I remember noticing this when working on FFM and it still worked without it.

```suggestion
```

2021-07-20 21:25 UTC, JasonTheAdams commented
@knowler Sounds good. Please approve and merge. 👍

2021-07-20 21:29 UTC, knowler approved these changes
Great work, @JasonTheAdams.

2021-07-20 21:30 UTC, merged