Allow custom amount field in Donor Dasboard Subscription Management to be emptied
impress-org/givewp pull request #6001
Opened 2021-09-29 20:44 UTC by knowler

Resolves #5896

## Description

**Work in progress**

In the subscription management view of the donor dashboard, there is an input that appears when the user chooses "Custom Amount." This input previously would replace its empty state with the minimum allowed value. This seems like it is desirable, however, it is not. In fact, users without the knack of filling out forms on the Internet will find it impossible to change the value to an amount where the most significant digit is less than the most significant digit in the minimum value (e.g. the minimum is $5 and the user wants to update the value to $12, but needs to change it from $15, once they backspace once, so that the input $reads 1, the input will think the value is less than $5 and change it to $5, since $1 is less than $5, even though they intend to write $12).

This PR resolves this issue by not setting minimum and maximum values when the value in the input is outside of them. Instead, we simply validate the input on blur and provide the user the appropriate feedback they need to enter an acceptable amount.

The existing logic in these components was so hard to follow and, since I had redefined the functionality, I completely scrapped what was there. The implementation that I needed was far simpler and I reduced the complexity further by normalizing the amount, the minimum, and the maximum _before_ giving them to the controls. This means that the underlying controls work in a more controlled manner.

## Affects

- Subscription Management view of the Donor Dashboard.

## Visuals

Will add before marking ready.

## Testing Instructions

Will add before marking ready.

## Pre-review Checklist

- [ ] Acceptance criteria satisfied and marked in related issue
- [ ] Relevant `@since` tags included in DocBlocks
- [ ] Changes logged to the `Unreleased` section of `CHANGELOG.md`
- [ ] Includes unit and/or end-to-end tests
- [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2021-09-29 23:30 UTC, knowler commented
This is ready for review.

@DevinWalker I implemented a fairly simple validation error message, I just thought I should tag you in case you had any feedback on it.

2021-09-30 06:59 UTC, alaca approved these changes
Looks good and is much more optimized now. Great work, @knowler

2021-09-30 06:59 UTC, alaca commented on src/DonorDashboards/resources/js/app/components/subscription-manager/amount-control/index.js
> +const cx = ( ...classNames ) => classNames.filter( Boolean ).join( ' ' );
Cool.

2021-09-30 07:14 UTC, ravinderk requested changes
@knowler Did we test this with currency switcher?

2021-10-01 16:46 UTC, knowler commented
@ravinderk I tested this with Euros (which uses comma as separator) and it seems to work. If we need more extensive testing with currency switcher, then I will need some help as it took me a while to figure out a currency that worked with the payment gateway I was using (Stripe Credit Card).

2021-10-01 20:24 UTC, merged