feature: Add Donation Summary to form.
impress-org/givewp pull request #6061
Opened 2021-10-27 20:50 UTC by kjohnson

## Description

This PR adds a "donation summary" section to the form, which includes the following:

- Donation amount
- Donation frequency
- Donation fees (if applicable)
- Donation total

## Demo

A demo sandbox is available for ease of testing: https://light-caiman.w5.wpsandbox.pro/

## Known Issues

- [x] Sometimes, switching the payment gateway removes the donation summary... 🤦🏻
#6064
- [x] Responsive styles
#6095 

## Visuals

### Template Location
| Before Payment Fields | After Payment Fields |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/139289913-d4d86bf3-4119-4590-a597-42e3e6400368.png) | ![image](https://user-images.githubusercontent.com/10858303/139290408-cd393d48-16dd-4c6f-aa7c-0497025e1089.png) |

### Form Settings

| Enabled for new forms | Disabled for existing forms |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/139303728-1cf3d8c9-63e6-49fc-9a4a-884dc7eed689.png) | ![image](https://user-images.githubusercontent.com/10858303/139303817-b6a8d017-e7d9-4218-afdd-2c726324bce4.png) |

### GiveWP

![image](https://user-images.githubusercontent.com/10858303/139290863-822d5278-2a20-4555-83a9-0ed65c1599b5.png)

### Fee Recovery Add-on

![image](https://user-images.githubusercontent.com/10858303/139290969-06df6e2d-1629-4fa1-a1a3-4eeb3242ae0e.png)

### Reucrring Donations Add-on

| Opt-out | Opt-in |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/139291207-49afc9b5-5995-4058-ac6a-a844555eba66.png) | ![image](https://user-images.githubusercontent.com/10858303/139291338-d25072e7-bb1f-4232-8e15-45bcb49c6cbd.png) |

#### Admin Defined and Variable Recurring Duration

| | |
| --- | --- |
| ![Screen Shot 2021-11-04 at 14 59 28](https://user-images.githubusercontent.com/10858303/140402949-be55a156-bf29-4fc1-ac9b-0edbca0c9596.png) | ![Screen Shot 2021-11-04 at 14 59 56](https://user-images.githubusercontent.com/10858303/140403044-2c3cee3e-1025-4fbf-b1da-656f74d6b342.png) |

### Currency Switcher Add-on

| Pound Sterling | Japanese Yen |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/139291780-5b091ace-764f-456d-bc35-0384e229fb50.png) | ![image](https://user-images.githubusercontent.com/10858303/139291591-4083aa05-be51-4375-b416-5f0dd02ae8e9.png)  |

### Responsive Styling

| | |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/141220567-637ec716-712f-41f1-97e4-070894b29a6c.png) | ![image](https://user-images.githubusercontent.com/10858303/141220504-7385cad3-ba86-4124-998a-1526b7a0bac7.png) |
| ![image](https://user-images.githubusercontent.com/10858303/141220918-ec835060-9e9f-4536-9160-2df55f8e90cd.png) | ![image](https://user-images.githubusercontent.com/10858303/141220957-476ff2e5-9c85-47c7-afdb-8c3b4c81d7d6.png) |

## Testing Instructions

- Supports Recurring by updating the donation frequency
- Supports Fee Recovery by displaying the fee amount and the total amount
- Supports Currency Switcher by updating the currency in the summary (amount, fee, and total)
- Supports Currency Switcher with zero decimal currencies (ie Japanese Yen)
- Supports Currency Switcher with switched separators (ie Euros)

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [x] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2021-11-04 02:24 UTC, DevinWalker requested changes
Hey @kjohnson I just did a review of this PR using the sandbox you created and here's my feedback: https://www.loom.com/share/13f9e1e6c2494c14879e86eb26791e62

Please let me know if you have any questions and thanks for the hard work!

2021-11-04 15:06 UTC, kjohnson commented
- [ ] Hyperlinks should use form primary color
- [ ] Capitalize "edit donation"
- [ ] Add pencil icon to "edit donation"
- [ ] Co-locate settings with related step
- [ ] Add semi-colon to description default value
- [ ] Add "Leave blank to remove" for description
- [ ] Stack elements on smaller screens
- [ ] Recurring hyperlink font size
- [ ] Support admin defined and per tier periods

2021-11-08 05:57 UTC, ravinderk commented on src/DonationSummary/resources/views/summary.php
> +                            Edit Donation<?php include plugin_dir_path( __DIR__ ) . 'images/pencil.svg'; ?>
@kjohnson can we make text translatable in this view?

2021-11-09 16:59 UTC, DevinWalker requested changes
Hey @kjohnson I just reviewed it again and it's looking great! The one thing I saw was the way the summary looks on smaller screens isn't what I was expecting. I was thinking the line items would stack and be centered. Let me know if you agree or if you were thinking something else with your implementation.

Here's my testing video: https://www.loom.com/share/0db23939b6244cada4ed14da3f713047

2021-11-09 19:47 UTC, kjohnson commented
@DevinWalker the heading wasn't showing because I had moved (changed the name of) the setting, so you would have had to re-publish the get it to apply - so that won't be an issue for new donation forms.

2021-11-09 19:51 UTC, kjohnson commented
@DevinWalker the mobile styles that I added respected the original text-alignment in the description list format. What you are seeing are the rows shifting between each other, like a zipper. That said, I can update it to be centered if you would prefer.

2021-11-11 15:43 UTC, kjohnson commented
@DevinWalker I have updated the responsive styles from "stacked" to "compact"

| | |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/141220567-637ec716-712f-41f1-97e4-070894b29a6c.png) | ![image](https://user-images.githubusercontent.com/10858303/141220504-7385cad3-ba86-4124-998a-1526b7a0bac7.png) |
| ![image](https://user-images.githubusercontent.com/10858303/141220918-ec835060-9e9f-4536-9160-2df55f8e90cd.png) | ![image](https://user-images.githubusercontent.com/10858303/141220957-476ff2e5-9c85-47c7-afdb-8c3b4c81d7d6.png) |

2021-11-11 16:39 UTC, DevinWalker approved these changes
@kjohnson this looks great now 👍

2021-11-16 20:45 UTC, JasonTheAdams commented
@kjohnson I just started testing this. I pulled down the PR and checked an existing multi-step form. It _is_ showing the Donation Summary — shouldn't it not be for existing forms?

2021-11-16 21:02 UTC, kjohnson commented
@JasonTheAdams looks like something got lost in a merge - it should be fixed now, see https://github.com/impress-org/givewp/pull/6061/commits/1efb0a4e08fdba98d723eaf49f67c249e3aaf95b .

2021-11-16 22:32 UTC, JasonTheAdams commented
Thanks, @kjohnson! It looks like it's working, but I'm getting some kind of console error:
![image](https://user-images.githubusercontent.com/2024145/142076878-937aa73e-b1ac-448b-96cb-908c6c2b5a69.png)

2021-11-16 23:03 UTC, JasonTheAdams approved these changes
Just excellent work, @kjohnson! The UI looks great and is nicely responsive, and the code is well organized and well written. 👍 

I just have the one comment above for an error in the console, though it doesn't seem to be breaking anything. Please clean that up and merge this up!

2021-11-17 13:39 UTC, kjohnson commented
@JasonTheAdams I'm seeing a slightly different console error, which I have resolved. Can you confirm that this is the same error? The line numbers are similar.

2021-11-17 20:15 UTC, JasonTheAdams approved these changes
Working great! I'm excited to get this out! 🎉

2021-11-17 20:16 UTC, merged