Feature/limit gateway scope
impress-org/givewp pull request #6088
Opened 2021-11-09 18:09 UTC by jonwaldstein

Resolves #

## Description

## Affects

## Visuals

## Testing Instructions

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2021-11-09 21:44 UTC, jonwaldstein commented
@JasonTheAdams @ravinderk this is ready for review.  It mainly focuses on updating the gateway methods w/ gateway specific params. After this we can get started on the different return types to further limit responsibility of gateways.

2021-11-10 07:21 UTC, JasonTheAdams requested changes

2021-11-10 15:39 UTC, jonwaldstein commented on src/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayAdapter.php
> +        ]);
I see your point, I would like to keep the Gateway DTO's out of the form context though - so I just added a way to generate from the request DTO to clean things up bf8de159

2021-11-10 15:43 UTC, jonwaldstein commented on src/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayAdapter.php
> +        $registeredGateway->createPayment($gatewayPaymentData);
Yes that's how it currently works. The initial payment gets added as the parent payment of the subscription.

2021-11-10 15:48 UTC, jonwaldstein commented on src/PaymentGateways/DataTransferObjects/GatewayPaymentData.php
> +	public $price;
resolved 3587197d

2021-11-10 15:56 UTC, jonwaldstein commented on src/PaymentGateways/DataTransferObjects/GatewayPaymentData.php
> +    public $purchaseKey;
It's a unique identifier generated from the `process-donation` file. i've seen it used throughout different gateways and there's also a filter for it.

![Screen Shot 2021-11-10 at 10 53 05 AM](https://user-images.githubusercontent.com/10138447/141147105-1b2ccfe9-cbe8-4448-910b-612426f682c7.png)


![Screen Shot 2021-11-10 at 10 53 27 AM](https://user-images.githubusercontent.com/10138447/141147122-93cc9c37-ea0b-47fa-a19c-13d9fb647117.png)

2021-11-10 15:58 UTC, jonwaldstein commented on src/PaymentGateways/DataTransferObjects/GatewayPaymentData.php
> +     * @var CardInfo
resolved 0aa8c6a6

2021-11-10 16:01 UTC, jonwaldstein commented on src/Framework/PaymentGateways/PaymentGatewayRegister.php
> +        if (!isset($this->gateways[$id])) {
resolved 19257b74

2021-11-10 16:01 UTC, jonwaldstein commented on src/Framework/PaymentGateways/PaymentGatewayRegister.php
> +            throw new InvalidArgumentException("No migration exists with the ID {$id}");
resolved 19257b74

2021-11-10 19:14 UTC, JasonTheAdams commented on src/Framework/PaymentGateways/PaymentGatewayRegister.php
> +        $legacyPaymentGatewayRegisterAdapter->connectGatewayToLegacyPaymentGatewayAdapter($gatewayClass);
Only if they could have an undesired side-effect. If it's simple enough to reverse this we probably should to avoid potential bugs.

2021-11-10 19:18 UTC, JasonTheAdams commented on src/Framework/PaymentGateways/PaymentGatewayRegister.php
> +        $legacyPaymentGatewayRegisterAdapter->connectGatewayToLegacyPaymentGatewayAdapter($gatewayClass);
Ah, we're using closures for those hooks. Those are *not* easy to remove. Please think through this and make sure there isn't a potential bug waiting to bite us. If there isn't, this is fine; if there is, we'll need to think through how to reverse/prevent this.

2021-11-10 19:53 UTC, JasonTheAdams commented on src/PaymentGateways/DataTransferObjects/GatewayPaymentData.php
> +    public $purchaseKey;
Ah, I believe that's the unique ID as on the gateway.

2021-11-10 20:04 UTC, JasonTheAdams approved these changes
Great work, @jonwaldstein! Thank you for clarifying that the return types will be another PR. I think that's the last key piece to this. If the hook reversal isn't an issue, then this is good to go!

2021-11-10 21:12 UTC, jonwaldstein commented on src/Framework/PaymentGateways/PaymentGatewayRegister.php
> +        $legacyPaymentGatewayRegisterAdapter->connectGatewayToLegacyPaymentGatewayAdapter($gatewayClass);
I really don't see any potentials issues with this. Once a gateway is unregistered / not in the register list - it won't make it to those adapter actions at all. I made sure there was nothing else weird by unregistering the TestGateway and creating another gateway.  I did not run into any issue using the new one.

2021-11-10 21:13 UTC, merged