New: Venmo payments via PayPal are now accepted
impress-org/givewp pull request #6388
Opened 2022-04-27 15:33 UTC by kjohnson

Resolves #6386 

## Description

This PR enabled Venmo as a PayPal funding source.

## Visuals

![image](https://user-images.githubusercontent.com/10858303/165555711-d810d29c-4bbe-482d-9732-e14b33178e9b.png)

![image](https://user-images.githubusercontent.com/10858303/165555601-13420fc6-52ec-48e9-906a-de00b935ebcf.png)

## Testing Instructions

- Enable Venmo for PayPal
## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2022-04-27 16:50 UTC, LMNTL requested changes
This looks good so far! When I click on the 'Venmo' button, I'm getting the following error:
![image](https://user-images.githubusercontent.com/7819986/165577507-cc29c57b-af28-4a7e-a116-93cdbfabafa4.png)

Here are the full contents of the error object;
```
{
  buttonCorrelationID: "f445453c4d7b2"
  buttonSessionID: "uid_853aa3298a_mty6nda6mdc"
  clientID: "AbMGETAnJeEeTFVJE_cEim_bROArQQkK0RAvvlIpUBEJ2w7bFkhZeyY5YT7FAYFGTW-9gEOvQz0onurd"
  env: "production"
  err: "Error: Expected reject to be called with Error, got [object Null]\n    at e.n.reject (https://www.paypal.com/sdk/js?client-id=AbMGETAnJeEeTFVJE_cEim_bROArQQkK0RAvvlIpUBEJ2w7bFkhZeyY5YT7FAYFGTW-9gEOvQz0onurd&merchant-id=BT7P6Q6TNS4JG&components=hosted-fields,buttons&locale=en_US&disable-funding=credit&enable-funding=venmo&vault=false&intent=capture&currency=USD:2:67322)\n    at https://www.paypal.com/sdk/js?client-id=AbMGETAnJeEeTFVJE_cEim_bROArQQkK0RAvvlIpUBEJ2w7bFkhZeyY5YT7FAYFGTW-9gEOvQz0onurd&merchant-id=BT7P6Q6TNS4JG&components=hosted-fields,buttons&locale=en_US&disable-funding=credit&enable-funding=venmo&vault=false&intent=capture&currency=USD:2:67915\n\nError: Expected reject to be called with Error, got [object Null]\n    at k.error (https://www.paypal.com/sdk/js?client-id=AbMGETAnJeEeTFVJE_cEim_bROArQQkK0RAvvlIpUBEJ2w7bFkhZeyY5YT7FAYFGTW-9gEOvQz0onurd&merchant-id=BT7P6Q6TNS4JG&components=hosted-fields,buttons&locale=en_US&disable-funding=credit&enable-funding=venmo&vault=false&intent=capture&currency=USD:2:159313)\n    at Object.<anonymous> (https://www.paypal.com/sdk/js?client-id=AbMGETAnJeEeTFVJE_cEim_bROArQQkK0RAvvlIpUBEJ2w7bFkhZeyY5YT7FAYFGTW-9gEOvQz0onurd&merchant-id=BT7P6Q6TNS4JG&components=hosted-fields,buttons&locale=en_US&disable-funding=credit&enable-funding=venmo&vault=false&intent=capture&currency=USD:2:172343)\n    at JSON.parse (<anonymous>)\n    at o (https://www.paypal.com/sdk/js?client-id=AbMGETAnJeEeTFVJE_cEim_bROArQQkK0RAvvlIpUBEJ2w7bFkhZeyY5YT7FAYFGTW-9gEOvQz0onurd&merchant-id=BT7P6Q6TNS4JG&components=hosted-fields,buttons&locale=en_US&disable-funding=credit&enable-funding=venmo&vault=false&intent=capture&currency=USD:2:172206)\n    at se (https://www.paypal.com/sdk/js?client-id=AbMGETAnJeEeTFVJE_cEim_bROArQQkK0RAvvlIpUBEJ2w7bFkhZeyY5YT7FAYFGTW-9gEOvQz0onurd&merchant-id=BT7P6Q6TNS4JG&components=hosted-fields,buttons&locale=en_US&disable-funding=credit&enable-funding=venmo&vault=false&intent=capture&currency=USD:2:172355)\n    at u.on (https://www.paypal.com/sdk/js?client-id=AbMGETAnJeEeTFVJE_cEim_bROArQQkK0RAvvlIpUBEJ2w7bFkhZeyY5YT7FAYFGTW-9gEOvQz0onurd&merchant-id=BT7P6Q6TNS4JG&components=hosted-fields,buttons&locale=en_US&disable-funding=credit&enable-funding=venmo&vault=false&intent=capture&currency=USD:2:177015)\n    at ve (https://www.paypal.com/sdk/js?client-id=AbMGETAnJeEeTFVJE_cEim_bROArQQkK0RAvvlIpUBEJ2w7bFkhZeyY5YT7FAYFGTW-9gEOvQz0onurd&merchant-id=BT7P6Q6TNS4JG&components=hosted-fields,buttons&locale=en_US&disable-funding=credit&enable-funding=venmo&vault=false&intent=capture&currency=USD:2:177134)\n    at https://www.paypal.com/sdk/js?client-id=AbMGETAnJeEeTFVJE_cEim_bROArQQkK0RAvvlIpUBEJ2w7bFkhZeyY5YT7FAYFGTW-9gEOvQz0onurd&merchant-id=BT7P6Q6TNS4JG&components=hosted-fields,buttons&locale=en_US&disable-funding=credit&enable-funding=venmo&vault=false&intent=capture&currency=USD:2:183838\n    at Function.e.try (https://www.paypal.com/sdk/js?client-id=AbMGETAnJeEeTFVJE_cEim_bROArQQkK0RAvvlIpUBEJ2w7bFkhZeyY5YT7FAYFGTW-9gEOvQz0onurd&merchant-id=BT7P6Q6TNS4JG&components=hosted-fields,buttons&locale=en_US&disable-funding=credit&enable-funding=venmo&vault=false&intent=capture&currency=USD:2:70625)\n    at https://www.paypal.com/sdk/js?client-id=AbMGETAnJeEeTFVJE_cEim_bROArQQkK0RAvvlIpUBEJ2w7bFkhZeyY5YT7FAYFGTW-9gEOvQz0onurd&merchant-id=BT7P6Q6TNS4JG&components=hosted-fields,buttons&locale=en_US&disable-funding=credit&enable-funding=venmo&vault=false&intent=capture&currency=USD:2:183588"
  referer: "www.paypal.com"
  sdkCorrelationID: "f389501e9f269"
  sessionID: "uid_e49b3db7d5_mty6mze6mzg"
  time: "1651077616957"
  timestamp: "1651077616957"
  token: null
  user_id: "uid_853aa3298a_mty6nda6mdc"
}
```

Happening on Chrome 100.0.4896.127. I get variants of the same message in both test and live mode.

2022-04-27 16:50 UTC, LMNTL commented on src/PaymentGateways/PayPalCommerce/PayPalCommerce.php
> +            ],
Clarifying question: can admins with a PayPal account from outside of the US accept payments through Venmo?

2022-04-28 18:28 UTC, JasonTheAdams commented
@kjohnson @LMNTL This is pretty high priority. Can we please prioritize getting this working?

2022-04-28 19:55 UTC, kjohnson commented
@LMNTL hm.. I made no additional configuration

![image](https://user-images.githubusercontent.com/10858303/165834916-abf59f00-9496-422e-8c72-dbe939328d8a.png)

2022-04-28 19:59 UTC, kjohnson commented
Interestingly, I see it working in FireFox, but not Brave.

2022-04-29 19:54 UTC, kjohnson commented
@LMNTL looks like the error you are seeing is a separate bug with PayPal Commerce from validation. I'm passing that along to @ravinderk for consideration. It seems that our PayPal code isn't handling the email validation correctly.

2022-05-02 14:24 UTC, LMNTL approved these changes

2022-05-02 14:29 UTC, LMNTL commented
@kjohnson @JasonTheAdams Ah, you are absolutely right, I should've checked it against `develop` first. Approving this since it was an unrelated issue. Strangely, I'm able to reproduce it even when filling a real email address in the form.

2022-05-02 16:18 UTC, merged