Changed: Donors, Donations, and DonationForms repositories
impress-org/givewp pull request #6390
Opened 2022-04-28 09:02 UTC by alaca

Resolves #

## Description

This PR refactors the Donors, Donations, and DonationForms repositories and it moves the _request logic_ of each repository into the separate controller class. Also, the code is updated to use some of the PHP 7.0 features.

## Affects

 Donors, Donations, and DonationForms repositories

## Testing Instructions

These changes only affect the list tables of Donors, Donations, and Donation Forms pages, so to test this, it should be enough to simply visit these pages and check that everything is working correctly ( list table data is loaded, etc. )

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2022-04-29 21:56 UTC, JasonTheAdams requested changes
Left a code comment. When I tested this I'm immediately getting fatal errors on any of the list screens. Probably shouldn't do that. 😅

2022-04-29 21:56 UTC, JasonTheAdams commented on src/DonationForms/Repositories/DonationFormsRepository.php
> +            ->get();
Can't this get replaced with `count()`?

2022-05-02 07:57 UTC, alaca commented on src/DonationForms/Repositories/DonationFormsRepository.php
> +            ->get();
> Fatal error: Uncaught TypeError: Give\DonationForms\Endpoints\ListForms::formatAmount(): Argument #1 ($amount) must be of type string, null given, called in /Users/jasonadams/Local Sites/givewp/app/public/wp-content/plugins/give/src/DonationForms/Endpoints/ListForms.php on line 162 and defined in /Users/jasonadams/Local Sites/givewp/app/public/wp-content/plugins/give/src/DonationForms/Endpoints/ListForms.php on line 170

This is great, PHP 5.6 will allow that.

2022-05-02 08:14 UTC, alaca commented on src/DonationForms/Repositories/DonationFormsRepository.php
> +            ->get();
Resolved: 92efa996

2022-05-02 11:40 UTC, alaca commented
@JasonTheAdams I refactored this even more. I added `DonationFormsResponseData` DTO and `DonationFormMetaKeys` class so that we are in line with how we do things in Donations, Donors, etc.

2022-05-04 17:37 UTC, JasonTheAdams commented
@alaca I just merged in `develop` — where the tests are passing — but they're failing here. Mind looking into this?

2022-05-04 20:00 UTC, alaca commented
@JasonTheAdams all checks have passed.

2022-05-04 23:51 UTC, JasonTheAdams requested changes
@alaca Tests are passing and the code looks good, but I did find that permantently deleting forms isn't working:

![Screen Recording 2022-05-04 at 04 46 05 PM](https://user-images.githubusercontent.com/2024145/166842995-869c2393-1278-4a5b-baa5-c6c589cf8e2f.gif)

2022-05-11 15:56 UTC, alaca commented
@JasonTheAdams resolved 8f16fb1

2022-05-16 20:59 UTC, JasonTheAdams approved these changes
Great work, @alaca!

2022-05-16 21:28 UTC, merged