Fix: Tool tabs display correctly
impress-org/givewp pull request #6430
Opened 2022-05-23 18:16 UTC by JoshuaHungDinh

Resolves #6426

## Description

In ListTablePage.module.scss the default padding of #wpbody is removed. This is necessary to avoid odd spacing in "All Forms", "Donations" & "Donors". This style however will be applied to any page that contains the ListTable component. Both the Log & Data tab use this component. As a result it will have the default padding removed & uneven styles across the tool tabs.  This PR corrects this issue by reintroducing the same amount of padding to the specific tabs that are affected.

## Affects

Donations > Tools > Log & Data tabs

## Visuals
<img width="1530" alt="Log Tab" src="https://user-images.githubusercontent.com/75056371/169880601-e374f048-396c-4bc2-8abf-a6ac8fa2045a.png">

<img width="1530" alt="Data Tab" src="https://user-images.githubusercontent.com/75056371/169880613-0a1279c4-bbf4-4e16-9c7d-e6bfea61de56.png">

## Testing Instructions

1. View Donations > Tools > Log & Data tabs
2. Check that all tabs are spaced/styled the same
3. Check that Donations > All Forms, Donations & Donors are unaffected
4. Collapse Side Navigation and ensure spacing works as intended
## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [x] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2022-05-23 18:26 UTC, DevinWalker commented
@JoshuaHungDinh does this work properly when the WP-Admin sidebar navigation is collapsed?
![2022-05-23_11-26-05](https://user-images.githubusercontent.com/1571635/169883328-5394f131-c649-47f5-a507-a81ef8f4a1a6.png)

2022-05-23 19:14 UTC, JoshuaHungDinh commented
> 

@DevinWalker  Yes, I think it looks fine. Attached is a quick video.

https://user-images.githubusercontent.com/75056371/169889797-ed559161-c51a-4782-8fb0-5e0635421eff.mov

2022-05-23 19:15 UTC, JoshuaHungDinh commented
> > 
> 
> @DevinWalker Yes, I think it looks fine. Attached is a quick video.
> 
>  Collapse.Side.Navigation.mov

Actually sorry, the arrow is affected. Il take a look at that..

2022-05-24 18:04 UTC, ravinderk requested changes
![Screenshot](https://user-images.githubusercontent.com/1784821/170102018-ffd06dab-362c-430b-b110-dc7981d0832d.png)

@JoshuaHungDinh I noticed that we are adding `20px` `padding-left` on other GiveWP pages, Can we maintain consistency?

2022-06-07 22:26 UTC, JoshuaHungDinh commented
> ![Screenshot](https://user-images.githubusercontent.com/1784821/170102018-ffd06dab-362c-430b-b110-dc7981d0832d.png)
> 
> @JoshuaHungDinh I noticed that we are adding `20px` `padding-left` on other GiveWP pages, Can we maintain consistency?

@ravinderk Can you take another look at these changes please?
<img width="863" alt="Tools tab" src="https://user-images.githubusercontent.com/75056371/172493454-ba6de609-85f6-42a0-9387-b3f20969a226.png">

2022-06-09 04:30 UTC, ravinderk approved these changes
Fixes the issue.

2022-06-09 04:30 UTC, merged