Hotfix: allow valid export dates
impress-org/givewp pull request #6482
Opened 2022-06-23 12:53 UTC by ravinderk

Resolves #

## Description

## Affects

## Visuals

## Testing Instructions

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2022-06-23 16:57 UTC, JasonTheAdams requested changes
Thanks, @ravinderk! I tried exporting the donors with an empty start date and 104108731513857 as the end date... and it worked? I mean, it downloaded the donors and didn't crash anything. Does it just silently override invalid values?

2022-06-24 05:57 UTC, ravinderk commented on includes/admin/tools/views/html-admin-page-exports.php
> +                                $firstDonationDate = give(DonationRepository::class)->getFirstDonationDate();
fixed: https://github.com/impress-org/givewp/compare/efc9efd746c6...74824a20313f

2022-06-24 05:59 UTC, ravinderk commented on includes/admin/tools/export/class-export-earnings.php
>   * This class handles earnings export
I made changes in the `get_data` function. Move the get date logic from request to  `getDatesFromRequest` function

2022-06-24 06:25 UTC, ravinderk commented
> Thanks, @ravinderk! I tried exporting the donors with an empty start date and 104108731513857 as the end date... and it worked? I mean, it downloaded the donors and didn't crash anything. Does it just silently override invalid values?

@JasonTheAdams As per my understanding issue is with `Export Revenue and Donation Stats` instead of `Export Donors`. Let me know what do you think?

2022-06-28 23:14 UTC, JasonTheAdams approved these changes

2022-06-28 23:15 UTC, JasonTheAdams commented
@ravinderk I changed this up a little bit. Instead of having the repository return `DateTime` objects, I had it return the model. Models are a great way to simplify a lot of logic with the trade-off that often more data is retrieved than is necessary (as in this case). But this way we avoid a bunch of incredibly specific, single purpose functions being added in places like the repository. Now we have two functions, one for grabbing the first and another the latest donation, that can be used in many different scenarios.

2022-06-28 23:24 UTC, merged

2022-06-29 04:10 UTC, ravinderk commented
> @ravinderk I changed this up a little bit. Instead of having the repository return `DateTime` objects, I had it return the model. Models are a great way to simplify a lot of logic with the trade-off that often more data is retrieved than is necessary (as in this case). But this way we avoid a bunch of incredibly specific, single purpose functions being added in places like the repository. Now we have two functions, one for grabbing the first and another the latest donation, that can be used in many different scenarios.

@JasonTheAdams this make sense.