Fix/ Php errors from enabled comments inside the Donor Wall have been corrected
impress-org/givewp pull request #6485
Opened 2022-06-23 18:53 UTC by JoshuaHungDinh

Resolves #6477

## Description

This PR fixes two Php warnings/errors from within the Donor Wall & includes some small style updates for the block. We found that the test donation gateway was not saving  anonymous donations to the database.  This caused an error for donations marked as anonymous on the front end. 

- Undefined variable $donor has been corrected by being properly passed to the template.
- Undefined index ['_give_anonymous_donation'] has been corrected by being properly saved to the database.
- Donation amounts will no longer wrap to the next line.

## Affects

- Donor Wall
- Test gateway

## Visuals

https://user-images.githubusercontent.com/75056371/175374410-b6e16924-4a16-4667-bae4-0a980eb8822a.mov

## Testing Instructions

- Create a Donor Wall block
- Toggle 'Show Comments' on & view page for thrown errors.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2022-06-23 19:12 UTC, jonwaldstein approved these changes
@JoshuaHungDinh looks good! please pass this along to QA.

2022-06-24 12:26 UTC, Benunc approved these changes
This has been tested, and confirmed that all fixes work, as well as run through automated QA to ensure that all donation functionality still works.

2022-06-24 12:47 UTC, ravinderk commented on templates/shortcode-donor-wall.php
> +                            echo "<p class='give-donor-content__excerpt'>
@JoshuaHungDinh for full comment, you can use `give-donor-content__comment` class.

2022-06-24 12:49 UTC, ravinderk commented on templates/shortcode-donor-wall.php
>                          $comment = trim($donation['donor_comment']);
@JoshuaHungDinh can we escape comment value before display on forntend?

2022-06-24 12:57 UTC, ravinderk commented on includes/gateways/manual.php
> +        update_post_meta($payment, '_give_anonymous_donation', $is_anonymous);
@JoshuaHungDinh `_give_anonymous_donation ` metadata value should be an integer when stored in a database.

ref: https://github.com/impress-org/givewp/blob/b68aab707f5c42e339a8d8327b2b6bf2ba72ba17/src/Donations/Repositories/DonationRepository.php#L348

2022-06-24 12:57 UTC, ravinderk requested changes
@JoshuaHungDinh I requested few changes. Let me know if you have any questions.

2022-06-27 06:13 UTC, ravinderk approved these changes

2022-06-27 06:13 UTC, merged