Fix: anonymous donations are now supported across donation types
impress-org/givewp pull request #6509
Opened 2022-07-06 15:52 UTC by jonwaldstein

…n and gateway api registrar conditional

Resolves #

## Description

## Affects

## Visuals

## Testing Instructions

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2022-07-06 16:02 UTC, jonwaldstein commented
@ravinderk this is ready for review (moved over from give-recurring).  Please don't merge, QA is pending.

2022-07-06 16:42 UTC, ravinderk commented on includes/donors/actions.php
> +function updateAnonymousDonationForLegacyGateways($donationId)
@jonwaldstein can we add `give` prefix to the function?

2022-07-06 16:43 UTC, ravinderk commented on includes/donors/actions.php
> +    $gatewayId = give_get_meta($donationId,'_give_payment_gateway');
@jonwaldstein Can we set the third param to `true`. That means the function will return a string value.

2022-07-06 16:46 UTC, ravinderk commented on includes/donors/actions.php
> +add_action('give_insert_payment', 'updateAnonymousDonationForLegacyGateways', 10, 2);
@jonwaldstein We can remove the third and fourth param.

2022-07-06 16:47 UTC, ravinderk requested changes
@jonwaldstein I added a few suggestions. Let me know if you have any questions.

2022-07-06 17:23 UTC, jonwaldstein commented
@ravinderk all your comments have been addressed 294b1e95

2022-07-06 17:27 UTC, ravinderk requested changes
@jonwaldstein Can you fix failed tests?

2022-07-06 19:20 UTC, Benunc approved these changes
This has been tested by both @rickalday and myself. The only thing this does *not* fix is that existing anonymous donations still show, after updating. 

The fix for that is for users to manually mark those donations as anonymous.

I'm good to merge it.

2022-07-06 22:04 UTC, JasonTheAdams commented
@ravinderk Please approve this if it looks good to you and we'll get it out tomorrow.

2022-07-07 04:22 UTC, ravinderk approved these changes

2022-07-07 04:22 UTC, merged