Feature: New Donation, Donor and Subscription table empty state designs
impress-org/givewp pull request #6710
Opened 2023-02-24 18:22 UTC by JoshuaHungDinh

Resolves #6709

## Description

This PR replaces the empty state static messages  on the Donor, Donation and Subscription tables if no results are found.

## Affects

- List tables

## Visuals & Testing Instructions

https://www.loom.com/share/5c60105c2a104115a578cfaf3cb7ff28

- Delete all Donations, Donors and Subscriptions.
- View each table for new design.
- Follow each link on each table.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2023-02-24 21:12 UTC, pauloiankoski approved these changes
Nice job!

2023-03-08 21:33 UTC, Benunc requested changes
The docs shortlinks should be used, as noted in the Review comments.

2023-03-08 21:33 UTC, Benunc commented on src/Donations/resources/components/DonationsListTable.tsx
> +            href={'https://givewp.com/documentation/core/donations'}
```suggestion
            href={'https://docs.givewp.com/donations'}
```

2023-03-08 21:33 UTC, Benunc commented on src/Donors/resources/components/DonorsListTable.tsx
> +            href={'https://givewp.com/documentation/core/donors/'}
```suggestion
            href={'https://docs.givewp.com/donors'}
```

2023-03-08 21:33 UTC, Benunc commented on src/Subscriptions/resources/components/SubscriptionsListTable.tsx
> +            href={'https://givewp.com/documentation/add-ons/recurring-donations'}
```suggestion
            href={'https://docs.givewp.com/subscriptions'}
```

2023-03-09 02:14 UTC, JoshuaHungDinh commented on src/Donors/resources/components/DonorsListTable.tsx
> +            href={'https://givewp.com/documentation/core/donors/'}
Resolved: https://github.com/impress-org/givewp/pull/6710/commits/79f2f46f22b6e4fc0632a0b9dc2745f535bac32d

2023-03-09 02:15 UTC, JoshuaHungDinh commented on src/Donations/resources/components/DonationsListTable.tsx
> +            href={'https://givewp.com/documentation/core/donations'}
Resolved: https://github.com/impress-org/givewp/pull/6710/commits/79f2f46f22b6e4fc0632a0b9dc2745f535bac32d

2023-04-24 14:12 UTC, Benunc commented
There's still a non-shortlink link on the Forms blank slate. I've passed that to Taylor for a new link there.

2023-04-24 17:55 UTC, JoshuaHungDinh commented on src/DonationForms/resources/components/DonationFormsListTable.tsx
> +        href={'https://docs.givewp.com/forms'}
@Benunc Updated short link has been added.

2023-04-24 18:18 UTC, Benunc approved these changes
This is all set. :shipit:

2023-04-24 19:22 UTC, merged