refactor: Add support for orderID via`gateway data
impress-org/givewp pull request #6723
Opened 2023-03-07 17:17 UTC by kjohnson

## Description

This PR adds support for passing the PayPal Order ID via the Gateway Data.

Previously, the Order ID was pulled directly from the `$_POST` global, which resulted in a `PayPalOrderIdException` for a missing Order ID in the Next Gen PayPal Commerce gateway implementation.

## Testing Instructions

Make a donation using the Next Gen updated PayPal Commerce gateway.

2023-03-24 19:59 UTC, jonwaldstein requested changes

2023-03-24 19:59 UTC, jonwaldstein commented on src/PaymentGateways/Actions/RegisterPaymentGateways.php
> +                $gatewayData['paypalOrder'] = (new GetPayPalOrderFromRequest())($gatewayData['payPalOrderId']);
@kjohnson can we clean this up a bit while we're here?

`GetPayPalOrderFromRequest`(by it's name) should either have all the request logic for retrieving the `payPalOrderId` or we can do the request logic here and just call `give(PayPalOrder::class)->getOrder($paypalOrderId)` directly without the action.

Both ways should be using a try/catch as well.

2023-03-28 13:22 UTC, jonwaldstein approved these changes
@kjohnson thanks for the update, looks much better.  Just to be safe, we should probably send this to QA to make sure it doesn't affect existing PayPal commerce/donations.

2023-03-28 13:30 UTC, kjohnson commented
Added to the QA pipeline, see https://app.asana.com/0/1203193833018151/1204267265032333/f.

2023-03-30 21:46 UTC, Benunc commented
@kjohnson I ran tests on this ZIP and it worked, too: https://github.com/impress-org/givewp/actions/runs/4568552280

:shipit:

2023-03-31 13:35 UTC, merged