Fix: add extra escaping to form grid shortcode attributes
impress-org/givewp pull request #6724
Opened 2023-03-07 20:00 UTC by jonwaldstein

## Description

This adds extra escaping to the form grid shortcode attribute rendering to prevent XSS.

## Affects

The form grid shortcode

## Visuals

N/A

## Testing Instructions

Make sure the form grid shortcode works as expected.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204137775197143

2023-03-07 20:34 UTC, jonwaldstein commented
@kjohnson @pauloiankoski this is ready for review.

2023-03-07 20:47 UTC, pauloiankoski requested changes

2023-03-07 20:47 UTC, pauloiankoski commented on templates/shortcode-form-grid.php
>                                          echo $button_text ?: __('Donate', 'give'); ?>
`$button_text` should be escaped.

2023-03-07 22:53 UTC, jonwaldstein commented on templates/shortcode-form-grid.php
>                                          echo $button_text ?: __('Donate', 'give'); ?>
resolved e8806385

2023-03-08 01:15 UTC, pauloiankoski approved these changes
Looks good. Ready for QA.

2023-03-08 15:25 UTC, kjohnson commented
I'm re-running failed jobs (looks like a date comparison is off by a couple of seconds).

2023-03-08 19:36 UTC, Benunc approved these changes
Manually confirmed that the malicious shortcode (a) currently breaks on latest stable and (b) is fixed by this PR.

Also ran all automated tests. 

:shipit:

2023-03-08 21:55 UTC, merged