Feature: implement necessary tweaks to make the Webhooks addon properly work
impress-org/givewp pull request #6811
Opened 2023-05-25 17:29 UTC by glaubersilva

Resolves #

## Description

## Affects

## Visuals

## Testing Instructions

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2023-06-05 15:35 UTC, glaubersilva commented on composer.json
>          }
@JasonTheAdams Without that, the action scheduler is installed in the following path: 
`wp-content/plugins/give/wp-content/plugins/action-scheduler`

Seems that this problem just happens when the composer file also has the `composer/installers` package.

So, these additional instructions make sure that the action scheduler will be installed in this path:
 `wp-content/plugins/give/vendor/woocommerce/action-scheduler`
 
 More details here: https://sanjeebaryal.com.np/action-scheduler-installed-inside-wp-content-folder/

2023-06-05 15:38 UTC, JasonTheAdams commented on composer.json
>          }
Ohhh, right, because it's a WordPress plugin type composer package. Thanks!

2023-06-05 21:01 UTC, JasonTheAdams requested changes
I left some comments, @glaubersilva. There's one piece in particular that I think would be better to boy scout code to avoid future confusion.

2023-06-06 14:03 UTC, glaubersilva commented on src/DonorDashboards/Profile.php
>              ->pipe(new UpdateDonorAnonymousGiving);
My initial idea was to use just the model. But I realized the pipeline is updating info not present in the Donor model properties, like avatar and company name for example. 

This way, to not mix it too much and let the thing less messy, now I removed the name and email from the pipeline and did the updating using just the model. In the pipeline, I left just the info that I didn't find a correspondent property in the model.

Resolved in 4890463f02184f67563f835c5d1a6409afeef0ba

2023-06-06 14:03 UTC, glaubersilva commented on src/DonorDashboards/Pipeline/Stages/UpdateDonorName.php
> +    public function __construct(Donor &$donor)
Resolved in 4890463f02184f67563f835c5d1a6409afeef0ba

2023-06-06 14:04 UTC, glaubersilva commented on src/DonorDashboards/Pipeline/Stages/UpdateDonorName.php
> +    /**
Resolved in 4890463f02184f67563f835c5d1a6409afeef0ba

2023-06-06 19:34 UTC, JasonTheAdams approved these changes
We decided to clean up the pipeline in a subsequent PR. This is sufficient for now. Good work, @glaubersilva!

2023-06-06 19:41 UTC, merged