Refactor: use PayPal Client for api requests
impress-org/givewp pull request #6819
Opened 2023-06-05 05:08 UTC by ravinderk

Resolves #

## Description

## Affects

## Visuals

## Testing Instructions

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2023-07-18 16:07 UTC, JasonTheAdams requested changes
Looks good! Just a couple very minor changes!

2023-07-19 05:40 UTC, ravinderk commented on src/PaymentGateways/PayPalCommerce/Repositories/PayPalAuth.php
> +            throw new Exception('PayPal Commerce: Error retrieving access token with authorization code');
@JasonTheAdams I used `RuntimeException`.

I also used `UnexpectedValueException` when getting invalid access or a seller token.

2023-07-19 05:40 UTC, ravinderk commented on src/PaymentGateways/PayPalCommerce/PayPalClient.php
> +     * @deprecated x.x.x
fixed: https://github.com/impress-org/givewp/pull/6819/commits/ab536817894274a9b864631de8884d3aa291ceae

2023-07-27 23:29 UTC, JasonTheAdams approved these changes
Great! Please shoot this over to QA!

2023-07-31 15:57 UTC, rickalday approved these changes
Passed manual tests

2023-08-08 11:54 UTC, merged