Chore: add trait with auto getters and setters
impress-org/givewp pull request #6823
Opened 2023-06-07 18:40 UTC by pauloiankoski

## Description

## Affects

## Visuals

## Testing Instructions

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2023-06-07 21:24 UTC, JasonTheAdams commented
Nice, @pauloiankoski! I actually didn't know traits could use traits. That's cool!

As an API, I was imagining we'd do something like this:
```php
<?php

/**
 * @method foo(int $foo): self
 * @method getFoo(): int
 * @method getBar(): string
 * @method baz(string $baz): self
 */
class MyFancyClass {
  use HasGettersAndSetters;

  protected $foo; // can be set and get
  protected $bar; // can be get
  protected $baz; // can be set
  protected $trulyHidden;

  protected $getterProperties = ['bar'];

  protected $setterProperties = ['baz' => 'string'];

  protected $getterAndSetterProperties = ['foo' => 'int'];

}
```

This has a couple benefits:
1. Types can be enforced in the settesr
2. Only properties explicitly set to have getters/setters do.

cc: @jonwaldstein

2023-06-07 21:28 UTC, JasonTheAdams commented
I've also considered:
1. Adding `$gettersPrefix` and `$settersPrefix` protected properties, so a class can adjust the prefixes if they choose. By default, I think the getter should have a `get` prefix and setters should just be the property name.
2. Adding a `$settersAreFluent` protected (true by default) so classes can choose whether the setters return the class instance afterwards or not.

2023-06-07 21:36 UTC, kjohnson requested changes
@pauloiankoski can you add some unit tests for the getter and setter traits (as well as the HasGettersAndSetters trait)?

2023-06-07 21:36 UTC, kjohnson commented on src/Framework/FieldsAPI/Concerns/HasSetters.php
> +        if ($prefix === 'set') {
The `set` prefix isn't necessary here. We have already established a convention for setters in the Fields API without the prefix.

2023-06-07 21:50 UTC, JasonTheAdams commented
Oh yeah, as (genuinely) interesting as it was, @pauloiankoski, to have it split into multiple traits, I don't think it's really necessary if we're going the route of using properties to declare getter/setter proprties.

2023-06-09 13:57 UTC, jonwaldstein commented
> Nice, @pauloiankoski! I actually didn't know traits could use traits. That's cool!
> 
> As an API, I was imagining we'd do something like this:
> 
> ```
> <?php
> 
> /**
>  * @method foo(int $foo): self
>  * @method getFoo(): int
>  * @method getBar(): string
>  * @method baz(string $baz): self
>  */
> class MyFancyClass {
>   use HasGettersAndSetters;
> 
>   protected $foo; // can be set and get
>   protected $bar; // can be get
>   protected $baz; // can be set
>   protected $trulyHidden;
> 
>   protected $getterProperties = ['bar'];
> 
>   protected $setterProperties = ['baz' => 'string'];
> 
>   protected $getterAndSetterProperties = ['foo' => 'int'];
> 
> }
> ```
> 
> (Note: scroll to see the entire code snippet.)
> 
> This has a couple benefits:
> 
> 1. Types can be enforced in the settesr
> 2. Only properties explicitly set to have getters/setters do.
> 
> cc: @jonwaldstein

Looking at this, i'm concerned we're get into over-engineering territory and i'm genuinely wondering if it's any more convenient than adding the methods manually.  Between the different property syntaxes, their types, and the docblocks - at a certain point I think the manual methods - being a little more code redundancy - ends up simplifying this whole api.

2023-06-12 14:55 UTC, closed without merging

2023-06-12 15:40 UTC, pauloiankoski commented
We have decided to keep manually adding getters and setters to our classes, as this pull request would add more complexity than actually help us. We may revisit this in the future when we support newer versions of PHP, which would provide better support for our intended purpose.