feature: clean up old code and finish v2 compatibility
impress-org/givewp pull request #6919
Opened 2023-09-06 16:44 UTC by JasonTheAdams

## Description

This PR is a rebuild of the Offline gateway to make use of the Gateway API and be v2 + v3 compatible. It cleans up a bunch of the old code and should port everything over nicely. The ID and everything should be preserved such that it's full backwards-compatible.

Note, since there's now a Billing Address block, the billing address settings don't do anything anymore on v3 forms. It should still work on v2 forms, though.

To do:
- [ ] Add the form builder settings (minus the gateway setting):

<img width="810" alt="image" src="https://github.com/impress-org/givewp/assets/2024145/4eeeae21-5705-4447-b8b9-2f0f58b98f71">

## Affects

The offline donations gateway

## Visuals

<img width="663" alt="image" src="https://github.com/impress-org/givewp/assets/2024145/b99e26b4-50ea-4b02-b051-0acf346f562c">

## Testing Instructions

Make sure the Offline gateway works with v2 and v3 forms. Make sure to test out the various settings and emails related to offline.

## Pre-review Checklist

-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2023-09-07 19:49 UTC, JasonTheAdams commented
@jonwaldstein This is ready for review! Happy to hop on a call to review together if you feel that would speed things up.

2023-09-07 20:19 UTC, jonwaldstein commented
@JasonTheAdams i'm getting a bunch of errors when running `npm run dev`.  If you added a typescript package to support an existing package - the versions need to match up or else the types are coming from a different version.

<img width="1351" alt="Screenshot 2023-09-07 at 4 17 49 PM" src="https://github.com/impress-org/givewp/assets/10138447/87ba3f1d-e993-4025-afab-3743dce6e362">

2023-09-07 20:26 UTC, JasonTheAdams commented
@jonwaldstein Are you able to help with that? How do I know which version to use?

2023-09-07 20:30 UTC, jonwaldstein commented
> @jonwaldstein Are you able to help with that? How do I know which version to use?

The version of the `@types/{package}` and the actual `{package}` need to be as close as possible - since the `@types/{package}` is basically supplying types for that version of the package.   

Yes I can help

2023-09-07 20:55 UTC, jonwaldstein commented
@JasonTheAdams fyi there's some discrepencies between the latest `@types/wordpress__block-editor` version and `@wordpress/block-editor` - they're not in sync at the moment so removing for now.  we can solve this another time.

2023-09-07 21:06 UTC, jonwaldstein requested changes
Looking good, left a few comments.  You will also want to add a migration for the form settings to block attributes.

2023-09-07 21:10 UTC, JasonTheAdams commented on src/PaymentGateways/Gateways/Offline/OfflineGateway.php
> +class OfflineGateway extends PaymentGateway
Resolved in 37ddc7da6

2023-09-07 21:13 UTC, JasonTheAdams commented on src/PaymentGateways/Gateways/Offline/Actions/DisableGatewayWhenDisabledPerForm.php
> +        ['offlineEnabled' => $enabled] = $paymentGatewaysBlock->getAttributes();
Good catch. Resolved in f71b29857

2023-09-07 21:16 UTC, JasonTheAdams commented on src/FormBuilder/resources/js/form-builder/src/components/settings/PopoverContentWithTemplateTags/index.tsx
> +    useEditor,
I think that's most relevant for functions. I don't think it matters for props. But not a big deal, resolved in 2bcebdeee

2023-09-07 21:30 UTC, jonwaldstein commented
@JasonTheAdams are you going to update this PR with the migration as well?

2023-09-07 21:33 UTC, JasonTheAdams commented
> @JasonTheAdams are you going to update this PR with the migration as well?

Ah yes, good point! I'll do that now!

2023-09-07 21:52 UTC, JasonTheAdams commented
@jonwaldstein I added the migration code: 22fff1157

2023-09-07 22:00 UTC, jonwaldstein approved these changes
Nice job! ready for QA 💸

2023-09-08 00:00 UTC, rickalday approved these changes
Passed manual QA tests.

2023-09-08 00:02 UTC, merged