Send donor name, email and address to PayPal payment details
impress-org/givewp pull request #7040
Opened 2023-10-14 09:43 UTC by ravinderk

Resolves #

## Description

## Affects

## Visuals

## Testing Instructions

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2023-10-20 14:32 UTC, glaubersilva requested changes
@ravinderk Nice work! I left a comment about just a minor change.

2023-10-20 14:32 UTC, glaubersilva commented on src/PaymentGateways/PayPalCommerce/AjaxRequestHandler.php
> +                'address' => $donorAddress,
We need an unreleased tag for this change.

2023-10-20 14:36 UTC, glaubersilva approved these changes
@ravinderk Thanks for the changes, ready for QA!

2023-10-25 14:23 UTC, matheuswd approved these changes
Approved!

2023-10-25 15:39 UTC, ravinderk commented
Merging is blocked query resolved. [Checking query details in the Slack](https://lw.slack.com/archives/C04UT6UPERW/p1698239889286709?thread_ts=1692056039.090419&cid=C04UT6UPERW).

2023-10-30 16:18 UTC, ravinderk commented
@JasonTheAdams This pull request is ready to release. [Check the PayPal Team response for more details](https://lw.slack.com/archives/C04UT6UPERW/p1698678030124869?thread_ts=1692056039.090419&cid=C04UT6UPERW).

2023-11-02 15:38 UTC, merged