Refactor: Re-style Login block
impress-org/givewp pull request #7436
Opened 2024-07-04 01:36 UTC by pauloiankoski

Resolves [GIVE-809]

## Description
This pull request re-style the Login block to match the new designs.

## Affects
Login block

## Visuals
![CleanShot 2024-07-03 at 21 46 20](https://github.com/impress-org/givewp/assets/3921017/fd94f5ac-be6c-4079-9504-be187a21d8d3)
_Already have an account button on Form Builder_

![CleanShot 2024-07-03 at 21 56 34](https://github.com/impress-org/givewp/assets/3921017/9a7e3123-702d-4e97-b4cb-c7fb216843e4)
_Login form on the Form Builder_

![CleanShot 2024-07-03 at 22 07 51](https://github.com/impress-org/givewp/assets/3921017/b3a26e34-d881-420d-94de-52e74acbc970)
_Already have an account button on Donation Form_

![CleanShot 2024-07-03 at 22 27 40](https://github.com/impress-org/givewp/assets/3921017/115f939c-ecb2-4c79-b2fb-e24b17cfa513)
_Login form on the Donation Form_

## Testing Instructions
Make sure the login form keep working just like before.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2024-07-04 17:50 UTC, jdghinson approved these changes
Looks good!

2024-07-08 16:32 UTC, JoshuaHungDinh requested changes

2024-07-08 19:00 UTC, pauloiankoski commented on src/DonationForms/resources/registrars/templates/groups/Authentication.tsx
> +import styles from '../styles.module.scss';
@JoshuaHungDinh Is b52c8064b385e347e94ccaae62760a0c7440314d what you meant?

2024-07-09 14:53 UTC, JoshuaHungDinh commented on src/DonationForms/resources/registrars/templates/groups/Authentication.tsx
> +import styles from '../styles.module.scss';
Yep!

2024-07-09 14:53 UTC, JoshuaHungDinh approved these changes

2024-07-09 16:59 UTC, rickalday approved these changes
Passed manual QA tests.

2024-07-09 18:26 UTC, merged