Refactor: change add form link and use WP button classes
impress-org/givewp pull request #7462
Opened 2024-07-25 19:56 UTC by glaubersilva

Resolves [GIVE-999]

## Description

## Affects

## Visuals

## Testing Instructions

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2024-07-26 13:23 UTC, jdghinson approved these changes
All good!

2024-07-29 16:03 UTC, pauloiankoski commented
@jdghinson Currently, the buttons are being styled slightly different from WP native buttons (32px vs 30px height and 500 vs 400 font-weight). Was that intentional?

![CleanShot 2024-07-29 at 13 02 20](https://github.com/user-attachments/assets/1aafff79-a61c-4671-9302-854969c952c9)
_Native on top, modified on bottom_

2024-07-29 16:06 UTC, jdghinson commented
@pauloiankoski Yes, the native looks smaller.

2024-07-29 17:05 UTC, pauloiankoski requested changes

2024-07-30 13:33 UTC, glaubersilva commented on src/Views/Components/ListTable/ListTablePage/ListTablePage.module.scss
> +}
Resolved in 630963f8535f09e282e8537cdd7951f08b3514f3

2024-07-30 13:34 UTC, glaubersilva commented
@pauloiankoski This is ready for re-review.

2024-07-30 15:03 UTC, pauloiankoski approved these changes
👍🏻

2024-07-30 18:09 UTC, rickalday approved these changes
Passed manual QA tests.

2024-07-30 18:27 UTC, merged