Feature: Add akismet support to v3 forms
impress-org/givewp pull request #7474
Opened 2024-08-02 17:16 UTC by kjohnson

Resolves [GIVE-1050]

## Description

This PR adds support for Akismet spam checks to the v3 donation forms.

## Affects

Adds the `givewp_donate_form_data_validated` filter `DonationFormRouteData`.

## Testing Instructions

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2024-08-02 19:20 UTC, kjohnson commented
Build for QA, see https://github.com/impress-org/givewp/actions/runs/10220925772.

2024-08-07 16:05 UTC, glaubersilva requested changes
@kjohnson Great work! I loved the unit tests cause they always helped me better understand everything. 😊 I just left a few comments about minor changes.

2024-08-07 18:03 UTC, kjohnson commented on src/DonationForms/Routes/DonateRoute.php
>          } catch (DonationFormFieldErrorsException $exception) {
I had considered that, but I didn't want the route error message to leak to a potential spammer. The donate controller routing suppresses the details when the error type is "unknown", which is intentional here.

In this case the exception error message is clear and is only available to the site admin (in the log).

2024-08-07 18:38 UTC, kjohnson commented on src/DonationSpam/Akismet/DataTransferObjects/CommentCheckArgs.php
> +    public static function make(DonateControllerData $data)
Resolved by [c0e49e6](https://github.com/impress-org/givewp/pull/7474/commits/c0e49e6f437f9f17c5263e5c579f06b058a7766c).

2024-08-07 18:39 UTC, kjohnson commented on src/DonationSpam/Akismet/DataTransferObjects/CommentCheckArgs.php
> +    public static function make(DonateControllerData $data)
Resolved by [c0e49e6](https://github.com/impress-org/givewp/pull/7474/commits/c0e49e6f437f9f17c5263e5c579f06b058a7766c).

2024-08-07 18:39 UTC, kjohnson commented on src/DonationSpam/Akismet/DataTransferObjects/CommentCheckArgs.php
> +    public function toHttpQuery()
Resolved by [c0e49e6](https://github.com/impress-org/givewp/pull/7474/commits/c0e49e6f437f9f17c5263e5c579f06b058a7766c).

2024-08-07 19:19 UTC, kjohnson commented on src/DonationSpam/ServiceProvider.php
> +            && give_check_akismet_key();
That would mean that the setting's configuration would be referencing itself.

```diff
[
    'name'    => __( 'Akismet SPAM Protection', 'give' ),
    'id'      => 'akismet_spam_protection*,
-   'default' => ( give_check_akismet_key() ) ? 'enabled' : 'disabled',
+   'default' => (give_is_setting_enabled(give_get_option('akismet_spam_protection'))) ? 'enabled' : 'disabled',
],
```

2024-08-07 19:22 UTC, kjohnson commented on src/DonationSpam/ServiceProvider.php
> +            && give_check_akismet_key();
If we call `give_check_akismet_key()` first, then we can assume a default value of `enabled` for the `akismet_spam_protection` option.

```php
public function isAkismetEnabledAndConfigured(): bool
{
    return
        give_check_akismet_key()
        && give_is_setting_enabled(
            give_get_option( 'akismet_spam_protection', 'enabled')
        );
}
```

2024-08-07 19:26 UTC, kjohnson commented on tests/Unit/DonationSpam/Akismet/Actions/ValidateDonationTest.php
> +final class ValidateDonationTest extends TestCase
Resolved, see [c6db18e](https://github.com/impress-org/givewp/pull/7474/commits/c6db18e17d72fe7220abd6feca628cf8855e1dc2).

2024-08-07 19:55 UTC, glaubersilva commented on src/DonationForms/Routes/DonateRoute.php
>          } catch (DonationFormFieldErrorsException $exception) {
Got it. Thanks for the clarification!

2024-08-07 19:55 UTC, glaubersilva commented on src/DonationSpam/ServiceProvider.php
> +            && give_check_akismet_key();
Oh yeah, it makes more sense. Thanks for the changes!

2024-08-07 19:56 UTC, glaubersilva approved these changes
@kjohnson Looks good to me, ready for QA. Great work!

2024-08-14 16:04 UTC, rickalday approved these changes
Passed manual QA tests.

2024-08-14 16:11 UTC, merged