Fun: UserPermissions facade
impress-org/givewp pull request #7491
Opened 2024-08-16 20:35 UTC by jonwaldstein

Resolves #

## Description

The UserPermissions Facade is a class that allows you to check if a user has a specific capability or role. It is a wrapper around the WordPress `current_user_can()` function but geared toward the roles in GiveWP.

Example:

```php
use Give\Framework\Permissions\Permissions;

if (!UserPermissions::donationForms()->can('edit')) {
    throw new Exception('You do not have permission to edit donation forms.');
}
```

## Affects

## Visuals

N/A

## Testing Instructions

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2025-01-17 20:08 UTC, jonwaldstein commented
This was a good spike/exploration but i'm not sure I like the api anymore 😄 .  I'm going to close for now and potentially explore a different, simpler direction that doesn't try to abstract away too much.

2025-01-17 20:08 UTC, closed without merging

2025-12-12 18:01 UTC, jonwaldstein commented
I've decided to revive this API 👽

2025-12-12 19:12 UTC, pauloiankoski requested changes
Left comments about some small details. One last question: do you think it would be worth registering `UserPermissionsFacade::class` as a singleton in a service provider? The idea would be to prevent multiple instances of that class from being created.

2025-12-12 19:12 UTC, pauloiankoski commented on src/Framework/Permissions/Facades/UserPermissions.php
> + * @method static DonorPermissions donors()
The `@method` annotations in the facade class seem to be incomplete.

```suggestion
 * @method static DonationFormPermissions donationForms()
 * @method static DonationPermissions donations()
 * @method static DonorPermissions donors()
 * @method static CampaignPermissions campaigns()
 * @method static ReportsPermissions reports()
 * @method static SensitiveDataPermissions sensitiveData()
 * @method static SettingsPermissions settings()
```

2025-12-12 19:12 UTC, pauloiankoski commented on src/Framework/Permissions/Traits/WithPrivatePermissions.php
> +        return $this->currentUserCan('read_private');
Since this trait relies on a method that may not exist in the context where it’s used, do you think we could add a check like `method_exists($this, 'currentUserCan')` before calling it?

2025-12-12 19:33 UTC, jonwaldstein commented on src/Framework/Permissions/Facades/UserPermissions.php
> + * @method static DonorPermissions donors()
oh yeah good catch!

2025-12-12 20:20 UTC, jonwaldstein commented on src/Framework/Permissions/Traits/WithPrivatePermissions.php
> +        return $this->currentUserCan('read_private');
Yeah you're right, I ended up removing it as we can tackle more specifics needed later during implementation de14bd66

2025-12-12 20:25 UTC, jonwaldstein commented
@pauloiankoski I made some updates and I have some more ideas but will wait until implementation before overcomplicating this 😄 

Regarding your question about registering this as a singleton - the Facade class actually already[ does that for us](https://github.com/impress-org/givewp/blob/42b82ca57a18193c46fd320c6a26132ec4e9529d/src/Framework/Support/Facades/Facade.php#L35).  The only difference is it's done at runtime (which I think make sense for permissions) so the first time you use the Facade it will become a singleton and subsequent usage will use the same instance.

2025-12-12 20:32 UTC, pauloiankoski approved these changes
Looks really good. This will make working with permissions much easier.