Feature: Add campaign title block
impress-org/givewp pull request #7648
Opened 2024-12-12 14:36 UTC by pauloiankoski

Resolves [GIVE-1959]

## Description
This pull request lays the foundation for future Campaign-related blocks by introducing key structural elements. The updates in this PR include:
- **Dynamic Block Registration**: Registers blocks dynamically based on their block.json files.
- **Campaign Page REST API**: Adds `campaignId` as a field to the REST API response for the Campaign Page CPT.
- **Custom Hooks and Shared Components**: Introduces reusable hooks and components to simplify campaign selection or retrieval from context within campaign blocks.
- **Initial Campaign Title Block**: Adds a basic Campaign Title block to serve as a reference and model for upcoming blocks.

These changes establish a scalable and flexible structure for Campaign blocks, enabling more streamlined development of future features.

## Visuals
![CleanShot 2024-12-12 at 11 30 34](https://github.com/user-attachments/assets/e6e5c4ed-ff18-42df-a69e-1076523d0245)

## Testing Instructions
1.	**Test on a Campaign Page**:
- Open a Campaign Page.
- Add the Campaign Title block.
- Verify that the block renders automatically, displaying the corresponding campaign title.
2.	**Test on Other Pages**:
- Open any other page type (not a Campaign Page).
- Add the Campaign Title block.
- Ensure that a campaign selector is displayed.
- Select a campaign from the selector.
- Verify that the block updates and renders the title of the selected campaign.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

[GIVE-1959]: https://stellarwp.atlassian.net/browse/GIVE-1959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2025-01-13 19:55 UTC, glaubersilva reviewed
@pauloiankoski I'm trying to compile it with `npm run dev` but I'm receiving multiple errors in the console as you can see here:

```
ERROR in C:\Users\glaub\Local Sites\givewp\app\public\wp-content\plugins\give\src\Campaigns\Blocks\CampaignTitleBlock\edit.tsx
23:35-42
[tsl] ERROR in C:\Users\glaub\Local Sites\givewp\app\public\wp-content\plugins\give\src\Campaigns\Blocks\CampaignTitleBlock\edit.tsx(23,36)
      TS2339: Property 'getSite' does not exist on type 'never'.

ERROR in C:\Users\glaub\Local Sites\givewp\app\public\wp-content\plugins\give\src\Campaigns\Blocks\shared\hooks\useCampaignId.ts
5:47-65
[tsl] ERROR in C:\Users\glaub\Local Sites\givewp\app\public\wp-content\plugins\give\src\Campaigns\Blocks\shared\hooks\useCampaignId.ts(5,48)
      TS2339: Property 'getCurrentPostType' does not exist on type 'never'.

ERROR in C:\Users\glaub\Local Sites\givewp\app\public\wp-content\plugins\give\src\Campaigns\Blocks\shared\hooks\useCampaignId.ts
8:41-63
[tsl] ERROR in C:\Users\glaub\Local Sites\givewp\app\public\wp-content\plugins\give\src\Campaigns\Blocks\shared\hooks\useCampaignId.ts(8,42)
      TS2339: Property 'getEditedPostAttribute' does not exist on type 'never'.
```

Any idea?

**P.S.:** I already removed the `node_modules` folder and ran the `npm install` again just to make sure.

![npm-dev-errors](https://github.com/user-attachments/assets/0f024915-3fd1-4d02-bcea-0ce48679c780)

2025-01-13 19:58 UTC, pauloiankoski commented
@GlauberSilva We might need to add `ts-ignore` to all those errors since they are part of the internal data API.

2025-01-13 20:31 UTC, glaubersilva commented
@pauloiankoski Thanks for the update! I was able to compile it and see the block working on the campaign page. However, when I created a new regular page and added the block, I wasn't able to select a campaign because the selector only displayed the _"No campaigns found"_ message. 

![image](https://github.com/user-attachments/assets/1b174c38-511b-4248-9465-334d77aecf08)

One more thing I would like to clarify about the page title of the campaign page (CPT). 

Does the expected behavior display the _"No title"_ string and prevent users from editing it?

![image](https://github.com/user-attachments/assets/798cf94c-4cba-4839-9899-d64df645b386)

2025-01-13 20:43 UTC, pauloiankoski commented
The "No campaign found" message is regarding an issue with our Campaign API endpoint.

![CleanShot 2025-01-13 at 17 42 31](https://github.com/user-attachments/assets/e04b7236-bbae-4904-baad-ded30cfaf9d9)

We have discussed about that but maybe it has not been tackled.

2025-01-13 20:44 UTC, pauloiankoski commented
The issue with the title is something to be addressed in a separated task where we may be syncing the Campaign title with the landing page title.

2025-01-13 21:42 UTC, glaubersilva requested changes
@pauloiankoski I did the first round of reviews and left a few comments with some suggestions. Tomorrow I'll do another round.

2025-01-13 21:42 UTC, glaubersilva commented on wordpress-scripts-webpack.config.js
> +const fs = require('fs');
Do we still need this?

2025-01-13 21:42 UTC, glaubersilva commented on src/Campaigns/Actions/RegisterCampaignBlocks.php
> +    public function __invoke()
Let's add a `@unreleased` tag here.

2025-01-13 21:42 UTC, glaubersilva commented on src/Campaigns/Actions/RegisterCampaignBlocks.php
> +            register_block_type(dirname(__DIR__) . '/Blocks/' . basename($block));
I think we can simplify this line, just like this:

```
register_block_type($block);
```

2025-01-13 21:42 UTC, glaubersilva commented on src/Campaigns/Actions/RegisterCampaignBlocks.php
> +    private function enqueueBlocksAssets()
Let's add a `@unreleased` tag here.

2025-01-13 21:42 UTC, glaubersilva commented on src/Campaigns/Actions/RegisterCampaignIdRestField.php
> +    public function __invoke()
Let's add a `@unreleased` tag here.

2025-01-13 21:42 UTC, glaubersilva commented on src/Campaigns/Blocks/CampaignTitleBlock/edit.tsx
> +                                        rel="noopener noreferrer"
Let's add an aria-label attribute here, something like this:

```
aria-label={__('Edit campaign settings in a new tab', 'give')}
```

2025-01-14 13:52 UTC, glaubersilva requested changes
@pauloiankoski Nice work! I left just a few more comments in my second round of reviews. As a note, I was a bit picky with the details while reviewing the code, as this is the first block that will serve as the foundation for others so I was trying to make sure we'll have a solid base for the next blocks. Thanks in advance for your understanding. 🙂

2025-01-14 13:52 UTC, glaubersilva commented on src/Campaigns/Blocks/CampaignTitleBlock/block.json
> +            "type": "string"
Would it be interesting to add some default value for this attribute? E.g: `"default": "left"`

2025-01-14 13:52 UTC, glaubersilva commented on src/Campaigns/Blocks/shared/components/CampaignDropdown.tsx
> +import {Campaign} from '@givewp/campaigns/admin/components/types';
Can we remove this not-used import statement?

2025-01-14 13:52 UTC, glaubersilva commented on src/Campaigns/Blocks/CampaignTitleBlock/render.php
> +if (empty($attributes) || !isset($attributes['campaignId'])) {
I'm not sure if we need to use `empty($attributes)` as part of the condition. It seems it would be enough to use only the second checking, something like this:

```
if (!isset($attributes['campaignId'])) {
    return;
}
```

2025-01-14 13:52 UTC, glaubersilva commented on src/Campaigns/Blocks/shared/components/CampaignDropdown.tsx
> +            onChange={(newValue) => setAttributes({campaignId: newValue ? parseInt(newValue) : null})}
Can we add the type for the newValue param?

2025-01-14 13:52 UTC, glaubersilva commented on src/Campaigns/Blocks/shared/hooks/useCampaign.ts
> +export default function useCampaign(campaignId) {
Can we add the type for `campaignId`?

2025-01-15 14:54 UTC, pauloiankoski commented on src/Campaigns/Actions/RegisterCampaignBlocks.php
> +    public function __invoke()
Resolved: d3b071a4d128f29dfc4031b6a1b2c47c77fa6fca

2025-01-15 14:54 UTC, pauloiankoski commented on src/Campaigns/Actions/RegisterCampaignBlocks.php
> +    private function enqueueBlocksAssets()
Resolved: d3b071a4d128f29dfc4031b6a1b2c47c77fa6fca

2025-01-15 14:55 UTC, pauloiankoski commented on src/Campaigns/Actions/RegisterCampaignIdRestField.php
> +    public function __invoke()
Resolved: d3b071a4d128f29dfc4031b6a1b2c47c77fa6fca

2025-01-15 14:55 UTC, pauloiankoski commented on wordpress-scripts-webpack.config.js
> +const fs = require('fs');
5f63fe0157fc24a20547aabf7eb571dd2f5d9d80

2025-01-15 15:25 UTC, pauloiankoski commented on src/Campaigns/Actions/RegisterCampaignIdRestField.php
> +class RegisterCampaignIdRestField
Resolved: d3b071a4d128f29dfc4031b6a1b2c47c77fa6fca

2025-01-15 15:25 UTC, pauloiankoski commented on src/Campaigns/Blocks/CampaignTitleBlock/edit.tsx
> +                        <BaseControl label="Title">
https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/base-control/README.md#id

Per the docs, the only required attribute is `children`. Anyway, added here: 817d364adf5ec5a6e2f46785bc6ab821988c0d89

2025-01-15 15:25 UTC, pauloiankoski commented on src/Campaigns/Blocks/CampaignTitleBlock/edit.tsx
> +                                        rel="noopener noreferrer"
Resolved: 817d364adf5ec5a6e2f46785bc6ab821988c0d89

2025-01-15 15:40 UTC, pauloiankoski commented on src/Campaigns/Blocks/CampaignTitleBlock/edit.tsx
> +                    onChange={(nextAlign) => {
Resolved: a6aa8de7c766c3e25adf7f3d1dd8b8232d94fdc6

2025-01-15 15:40 UTC, pauloiankoski commented on src/Campaigns/Blocks/shared/components/CampaignDropdown.tsx
> +            onChange={(newValue) => setAttributes({campaignId: newValue ? parseInt(newValue) : null})}
Resolved: a6aa8de7c766c3e25adf7f3d1dd8b8232d94fdc6

2025-01-15 15:40 UTC, pauloiankoski commented on src/Campaigns/Blocks/shared/hooks/useCampaign.ts
> +export default function useCampaign(campaignId) {
Resolved: a6aa8de7c766c3e25adf7f3d1dd8b8232d94fdc6

2025-01-15 15:41 UTC, pauloiankoski commented on src/Campaigns/Blocks/shared/components/CampaignDropdown.tsx
> +import {Campaign} from '@givewp/campaigns/admin/components/types';
Resolved: 1da92bae836c144549774d5cbbada038a1da6c38

2025-01-15 15:41 UTC, pauloiankoski commented on src/Campaigns/Blocks/CampaignTitleBlock/render.php
> +if (empty($attributes) || !isset($attributes['campaignId'])) {
Resolved: 4b6df903c0da762a0ce6798fe4b6948124c3596d

2025-01-15 20:29 UTC, glaubersilva approved these changes
@pauloiankoski Thanks for the changes, great work man! 🚀

2025-01-16 19:16 UTC, merged